# Generated by Django 3.2.22 on 2023-10-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20231008_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='medicines',
        ),
    ]
