# Generated by Django 3.2.22 on 2023-10-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20231015_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('medicine_id', models.IntegerField()),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
