# Generated by Django 3.2.22 on 2023-10-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_ordermedicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='medicine_id',
        ),
    ]
